#!/bin/bash

## Description: Install or use node.
## Usage: nvm [flags] [args]
## Example: "nvm use or nvm install"

source /etc/profile && cd /var/www/html/web/themes/custom/training_theme && nvm $@
